/*
 * Payments
 * Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.PaymentInstruction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CaptureRequestAllOf
 */
public class CaptureRequestAllOfTest {
    private final CaptureRequestAllOf model = new CaptureRequestAllOf();

    /**
     * Model tests for CaptureRequestAllOf
     */
    @Test
    public void testCaptureRequestAllOf() {
        // TODO: test CaptureRequestAllOf
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'invoiceId'
     */
    @Test
    public void invoiceIdTest() {
        // TODO: test invoiceId
    }

    /**
     * Test the property 'finalCapture'
     */
    @Test
    public void finalCaptureTest() {
        // TODO: test finalCapture
    }

    /**
     * Test the property 'paymentInstruction'
     */
    @Test
    public void paymentInstructionTest() {
        // TODO: test paymentInstruction
    }

    /**
     * Test the property 'noteToPayer'
     */
    @Test
    public void noteToPayerTest() {
        // TODO: test noteToPayer
    }

    /**
     * Test the property 'softDescriptor'
     */
    @Test
    public void softDescriptorTest() {
        // TODO: test softDescriptor
    }

}
