/*
 * Payments
 * Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DisbursementMode;
import com.konfigthis.client.model.PlatformFee;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentInstruction
 */
public class PaymentInstructionTest {
    private final PaymentInstruction model = new PaymentInstruction();

    /**
     * Model tests for PaymentInstruction
     */
    @Test
    public void testPaymentInstruction() {
        // TODO: test PaymentInstruction
    }

    /**
     * Test the property 'platformFees'
     */
    @Test
    public void platformFeesTest() {
        // TODO: test platformFees
    }

    /**
     * Test the property 'disbursementMode'
     */
    @Test
    public void disbursementModeTest() {
        // TODO: test disbursementMode
    }

    /**
     * Test the property 'payeePricingTierId'
     */
    @Test
    public void payeePricingTierIdTest() {
        // TODO: test payeePricingTierId
    }

    /**
     * Test the property 'payeeReceivableFxRateId'
     */
    @Test
    public void payeeReceivableFxRateIdTest() {
        // TODO: test payeeReceivableFxRateId
    }

}
