/*
 * Payments
 * Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProcessorResponse
 */
public class ProcessorResponseTest {
    private final ProcessorResponse model = new ProcessorResponse();

    /**
     * Model tests for ProcessorResponse
     */
    @Test
    public void testProcessorResponse() {
        // TODO: test ProcessorResponse
    }

    /**
     * Test the property 'avsCode'
     */
    @Test
    public void avsCodeTest() {
        // TODO: test avsCode
    }

    /**
     * Test the property 'cvvCode'
     */
    @Test
    public void cvvCodeTest() {
        // TODO: test cvvCode
    }

    /**
     * Test the property 'responseCode'
     */
    @Test
    public void responseCodeTest() {
        // TODO: test responseCode
    }

    /**
     * Test the property 'paymentAdviceCode'
     */
    @Test
    public void paymentAdviceCodeTest() {
        // TODO: test paymentAdviceCode
    }

}
