/*
 * Payments
 * Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LinkDescription;
import com.konfigthis.client.model.MerchantPayableBreakdown;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.PayeeBase;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RefundAllOf
 */
public class RefundAllOfTest {
    private final RefundAllOf model = new RefundAllOf();

    /**
     * Model tests for RefundAllOf
     */
    @Test
    public void testRefundAllOf() {
        // TODO: test RefundAllOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'invoiceId'
     */
    @Test
    public void invoiceIdTest() {
        // TODO: test invoiceId
    }

    /**
     * Test the property 'customId'
     */
    @Test
    public void customIdTest() {
        // TODO: test customId
    }

    /**
     * Test the property 'acquirerReferenceNumber'
     */
    @Test
    public void acquirerReferenceNumberTest() {
        // TODO: test acquirerReferenceNumber
    }

    /**
     * Test the property 'noteToPayer'
     */
    @Test
    public void noteToPayerTest() {
        // TODO: test noteToPayer
    }

    /**
     * Test the property 'sellerPayableBreakdown'
     */
    @Test
    public void sellerPayableBreakdownTest() {
        // TODO: test sellerPayableBreakdown
    }

    /**
     * Test the property 'payer'
     */
    @Test
    public void payerTest() {
        // TODO: test payer
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
