/*
 * Payments
 * Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExchangeRate;
import com.konfigthis.client.model.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the merchant holds their funds.
 */
@ApiModel(description = "The net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the merchant holds their funds.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class NetAmountBreakdownItem {
  public static final String SERIALIZED_NAME_PAYABLE_AMOUNT = "payable_amount";
  @SerializedName(SERIALIZED_NAME_PAYABLE_AMOUNT)
  private Money payableAmount;

  public static final String SERIALIZED_NAME_CONVERTED_AMOUNT = "converted_amount";
  @SerializedName(SERIALIZED_NAME_CONVERTED_AMOUNT)
  private Money convertedAmount;

  public static final String SERIALIZED_NAME_EXCHANGE_RATE = "exchange_rate";
  @SerializedName(SERIALIZED_NAME_EXCHANGE_RATE)
  private ExchangeRate exchangeRate;

  public NetAmountBreakdownItem() {
  }

  public NetAmountBreakdownItem payableAmount(Money payableAmount) {
    
    
    
    
    this.payableAmount = payableAmount;
    return this;
  }

   /**
   * Get payableAmount
   * @return payableAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Money getPayableAmount() {
    return payableAmount;
  }


  public void setPayableAmount(Money payableAmount) {
    
    
    
    this.payableAmount = payableAmount;
  }


  public NetAmountBreakdownItem convertedAmount(Money convertedAmount) {
    
    
    
    
    this.convertedAmount = convertedAmount;
    return this;
  }

   /**
   * Get convertedAmount
   * @return convertedAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Money getConvertedAmount() {
    return convertedAmount;
  }


  public void setConvertedAmount(Money convertedAmount) {
    
    
    
    this.convertedAmount = convertedAmount;
  }


  public NetAmountBreakdownItem exchangeRate(ExchangeRate exchangeRate) {
    
    
    
    
    this.exchangeRate = exchangeRate;
    return this;
  }

   /**
   * Get exchangeRate
   * @return exchangeRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExchangeRate getExchangeRate() {
    return exchangeRate;
  }


  public void setExchangeRate(ExchangeRate exchangeRate) {
    
    
    
    this.exchangeRate = exchangeRate;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the NetAmountBreakdownItem instance itself
   */
  public NetAmountBreakdownItem putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetAmountBreakdownItem netAmountBreakdownItem = (NetAmountBreakdownItem) o;
    return Objects.equals(this.payableAmount, netAmountBreakdownItem.payableAmount) &&
        Objects.equals(this.convertedAmount, netAmountBreakdownItem.convertedAmount) &&
        Objects.equals(this.exchangeRate, netAmountBreakdownItem.exchangeRate)&&
        Objects.equals(this.additionalProperties, netAmountBreakdownItem.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payableAmount, convertedAmount, exchangeRate, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetAmountBreakdownItem {\n");
    sb.append("    payableAmount: ").append(toIndentedString(payableAmount)).append("\n");
    sb.append("    convertedAmount: ").append(toIndentedString(convertedAmount)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("payable_amount");
    openapiFields.add("converted_amount");
    openapiFields.add("exchange_rate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to NetAmountBreakdownItem
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!NetAmountBreakdownItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NetAmountBreakdownItem is not found in the empty JSON string", NetAmountBreakdownItem.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `payable_amount`
      if (jsonObj.get("payable_amount") != null && !jsonObj.get("payable_amount").isJsonNull()) {
        Money.validateJsonObject(jsonObj.getAsJsonObject("payable_amount"));
      }
      // validate the optional field `converted_amount`
      if (jsonObj.get("converted_amount") != null && !jsonObj.get("converted_amount").isJsonNull()) {
        Money.validateJsonObject(jsonObj.getAsJsonObject("converted_amount"));
      }
      // validate the optional field `exchange_rate`
      if (jsonObj.get("exchange_rate") != null && !jsonObj.get("exchange_rate").isJsonNull()) {
        ExchangeRate.validateJsonObject(jsonObj.getAsJsonObject("exchange_rate"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NetAmountBreakdownItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NetAmountBreakdownItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NetAmountBreakdownItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NetAmountBreakdownItem.class));

       return (TypeAdapter<T>) new TypeAdapter<NetAmountBreakdownItem>() {
           @Override
           public void write(JsonWriter out, NetAmountBreakdownItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public NetAmountBreakdownItem read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             NetAmountBreakdownItem instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NetAmountBreakdownItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NetAmountBreakdownItem
  * @throws IOException if the JSON string is invalid with respect to NetAmountBreakdownItem
  */
  public static NetAmountBreakdownItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NetAmountBreakdownItem.class);
  }

 /**
  * Convert an instance of NetAmountBreakdownItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

