/*
 * Payments
 * Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Identifiers related to a specific resource.
 */
@ApiModel(description = "Identifiers related to a specific resource.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RelatedIds {
  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  private String orderId;

  public static final String SERIALIZED_NAME_AUTHORIZATION_ID = "authorization_id";
  @SerializedName(SERIALIZED_NAME_AUTHORIZATION_ID)
  private String authorizationId;

  public static final String SERIALIZED_NAME_CAPTURE_ID = "capture_id";
  @SerializedName(SERIALIZED_NAME_CAPTURE_ID)
  private String captureId;

  public RelatedIds() {
  }

  public RelatedIds orderId(String orderId) {
    
    
    if (orderId != null && orderId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for orderId. Length must be greater than or equal to 1.");
    }
    
    this.orderId = orderId;
    return this;
  }

   /**
   * Order ID related to the resource.
   * @return orderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Order ID related to the resource.")

  public String getOrderId() {
    return orderId;
  }


  public void setOrderId(String orderId) {
    
    
    if (orderId != null && orderId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for orderId. Length must be greater than or equal to 1.");
    }
    this.orderId = orderId;
  }


  public RelatedIds authorizationId(String authorizationId) {
    
    
    if (authorizationId != null && authorizationId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for authorizationId. Length must be greater than or equal to 1.");
    }
    
    this.authorizationId = authorizationId;
    return this;
  }

   /**
   * Authorization ID related to the resource.
   * @return authorizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Authorization ID related to the resource.")

  public String getAuthorizationId() {
    return authorizationId;
  }


  public void setAuthorizationId(String authorizationId) {
    
    
    if (authorizationId != null && authorizationId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for authorizationId. Length must be greater than or equal to 1.");
    }
    this.authorizationId = authorizationId;
  }


  public RelatedIds captureId(String captureId) {
    
    
    if (captureId != null && captureId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for captureId. Length must be greater than or equal to 1.");
    }
    
    this.captureId = captureId;
    return this;
  }

   /**
   * Capture ID related to the resource.
   * @return captureId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Capture ID related to the resource.")

  public String getCaptureId() {
    return captureId;
  }


  public void setCaptureId(String captureId) {
    
    
    if (captureId != null && captureId.length() < 1) {
      throw new IllegalArgumentException("Invalid value for captureId. Length must be greater than or equal to 1.");
    }
    this.captureId = captureId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RelatedIds instance itself
   */
  public RelatedIds putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelatedIds relatedIds = (RelatedIds) o;
    return Objects.equals(this.orderId, relatedIds.orderId) &&
        Objects.equals(this.authorizationId, relatedIds.authorizationId) &&
        Objects.equals(this.captureId, relatedIds.captureId)&&
        Objects.equals(this.additionalProperties, relatedIds.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, authorizationId, captureId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelatedIds {\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    authorizationId: ").append(toIndentedString(authorizationId)).append("\n");
    sb.append("    captureId: ").append(toIndentedString(captureId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("order_id");
    openapiFields.add("authorization_id");
    openapiFields.add("capture_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RelatedIds
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RelatedIds.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RelatedIds is not found in the empty JSON string", RelatedIds.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("order_id") != null && !jsonObj.get("order_id").isJsonNull()) && !jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if ((jsonObj.get("authorization_id") != null && !jsonObj.get("authorization_id").isJsonNull()) && !jsonObj.get("authorization_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authorization_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authorization_id").toString()));
      }
      if ((jsonObj.get("capture_id") != null && !jsonObj.get("capture_id").isJsonNull()) && !jsonObj.get("capture_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `capture_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("capture_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RelatedIds.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RelatedIds' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RelatedIds> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RelatedIds.class));

       return (TypeAdapter<T>) new TypeAdapter<RelatedIds>() {
           @Override
           public void write(JsonWriter out, RelatedIds value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RelatedIds read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RelatedIds instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RelatedIds given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RelatedIds
  * @throws IOException if the JSON string is invalid with respect to RelatedIds
  */
  public static RelatedIds fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RelatedIds.class);
  }

 /**
  * Convert an instance of RelatedIds to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

