/*
 * Payments
 * Call the Payments API to authorize payments, capture authorized payments, refund payments that have already been captured, and show payment information. Use the Payments API in conjunction with the <a href=\"/docs/api/orders/v2/\">Orders API</a>. For more information, see the <a href=\"/docs/checkout/\">PayPal Checkout Overview</a>.
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.Capture2;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.PaymentInstruction2;
import com.konfigthis.client.model.Refund;
import com.konfigthis.client.model.RefundRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class CapturesApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CapturesApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public CapturesApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call refundPaymentCall(String captureId, String payPalRequestId, String prefer, String payPalAuthAssertion, RefundRequest refundRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = refundRequest;

        // create path and map variables
        String localVarPath = "/v2/payments/captures/{capture_id}/refund"
            .replace("{" + "capture_id" + "}", localVarApiClient.escapeString(captureId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (payPalRequestId != null) {
            localVarHeaderParams.put("PayPal-Request-Id", localVarApiClient.parameterToString(payPalRequestId));
        }

        if (prefer != null) {
            localVarHeaderParams.put("Prefer", localVarApiClient.parameterToString(prefer));
        }

        if (payPalAuthAssertion != null) {
            localVarHeaderParams.put("PayPal-Auth-Assertion", localVarApiClient.parameterToString(payPalAuthAssertion));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call refundPaymentValidateBeforeCall(String captureId, String payPalRequestId, String prefer, String payPalAuthAssertion, RefundRequest refundRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'captureId' is set
        if (captureId == null) {
            throw new ApiException("Missing the required parameter 'captureId' when calling refundPayment(Async)");
        }

        return refundPaymentCall(captureId, payPalRequestId, prefer, payPalAuthAssertion, refundRequest, _callback);

    }


    private ApiResponse<Refund> refundPaymentWithHttpInfo(String captureId, String payPalRequestId, String prefer, String payPalAuthAssertion, RefundRequest refundRequest) throws ApiException {
        okhttp3.Call localVarCall = refundPaymentValidateBeforeCall(captureId, payPalRequestId, prefer, payPalAuthAssertion, refundRequest, null);
        Type localVarReturnType = new TypeToken<Refund>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call refundPaymentAsync(String captureId, String payPalRequestId, String prefer, String payPalAuthAssertion, RefundRequest refundRequest, final ApiCallback<Refund> _callback) throws ApiException {

        okhttp3.Call localVarCall = refundPaymentValidateBeforeCall(captureId, payPalRequestId, prefer, payPalAuthAssertion, refundRequest, _callback);
        Type localVarReturnType = new TypeToken<Refund>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class RefundPaymentRequestBuilder {
        private final String captureId;
        private Money amount;
        private String customId;
        private String invoiceId;
        private String noteToPayer;
        private PaymentInstruction2 paymentInstruction;
        private String payPalRequestId;
        private String prefer;
        private String payPalAuthAssertion;

        private RefundPaymentRequestBuilder(String captureId) {
            this.captureId = captureId;
        }

        /**
         * Set amount
         * @param amount  (optional)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder amount(Money amount) {
            this.amount = amount;
            return this;
        }
        
        /**
         * Set customId
         * @param customId The API caller-provided external ID. Used to reconcile API caller-initiated transactions with PayPal transactions. Appears in transaction and settlement reports. The pattern is defined by an external party and supports Unicode. (optional)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder customId(String customId) {
            this.customId = customId;
            return this;
        }
        
        /**
         * Set invoiceId
         * @param invoiceId The API caller-provided external invoice ID for this order. The pattern is defined by an external party and supports Unicode. (optional)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder invoiceId(String invoiceId) {
            this.invoiceId = invoiceId;
            return this;
        }
        
        /**
         * Set noteToPayer
         * @param noteToPayer The reason for the refund. Appears in both the payer&#39;s transaction history and the emails that the payer receives. The pattern is defined by an external party and supports Unicode. (optional)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder noteToPayer(String noteToPayer) {
            this.noteToPayer = noteToPayer;
            return this;
        }
        
        /**
         * Set paymentInstruction
         * @param paymentInstruction  (optional)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder paymentInstruction(PaymentInstruction2 paymentInstruction) {
            this.paymentInstruction = paymentInstruction;
            return this;
        }
        
        /**
         * Set payPalRequestId
         * @param payPalRequestId The server stores keys for 45 days. (optional)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder payPalRequestId(String payPalRequestId) {
            this.payPalRequestId = payPalRequestId;
            return this;
        }
        
        /**
         * Set prefer
         * @param prefer The preferred server response upon successful completion of the request. Value is:&lt;ul&gt;&lt;li&gt;&lt;code&gt;return&#x3D;minimal&lt;/code&gt;. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the &lt;code&gt;id&lt;/code&gt;, &lt;code&gt;status&lt;/code&gt; and HATEOAS links.&lt;/li&gt;&lt;li&gt;&lt;code&gt;return&#x3D;representation&lt;/code&gt;. The server returns a complete resource representation, including the current state of the resource.&lt;/li&gt;&lt;/ul&gt; (optional, default to return&#x3D;minimal)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder prefer(String prefer) {
            this.prefer = prefer;
            return this;
        }
        
        /**
         * Set payPalAuthAssertion
         * @param payPalAuthAssertion An API-caller-provided JSON Web Token (JWT) assertion that identifies the merchant. For details, see [PayPal-Auth-Assertion](/docs/api/reference/api-requests/#paypal-auth-assertion).&lt;blockquote&gt;&lt;strong&gt;Note:&lt;/strong&gt;For three party transactions in which a partner is managing the API calls on behalf of a merchant, the partner must identify the merchant using either a PayPal-Auth-Assertion header or an access token with target_subject.&lt;/blockquote&gt; (optional)
         * @return RefundPaymentRequestBuilder
         */
        public RefundPaymentRequestBuilder payPalAuthAssertion(String payPalAuthAssertion) {
            this.payPalAuthAssertion = payPalAuthAssertion;
            return this;
        }
        
        /**
         * Build call for refundPayment
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> A successful request returns the HTTP &lt;code&gt;201 Created&lt;/code&gt; status code and a JSON response body that shows refund details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            RefundRequest refundRequest = buildBodyParams();
            return refundPaymentCall(captureId, payPalRequestId, prefer, payPalAuthAssertion, refundRequest, _callback);
        }

        private RefundRequest buildBodyParams() {
            RefundRequest refundRequest = new RefundRequest();
            refundRequest.amount(this.amount);
            refundRequest.customId(this.customId);
            refundRequest.invoiceId(this.invoiceId);
            refundRequest.noteToPayer(this.noteToPayer);
            refundRequest.paymentInstruction(this.paymentInstruction);
            return refundRequest;
        }

        /**
         * Execute refundPayment request
         * @return Refund
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> A successful request returns the HTTP &lt;code&gt;201 Created&lt;/code&gt; status code and a JSON response body that shows refund details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public Refund execute() throws ApiException {
            RefundRequest refundRequest = buildBodyParams();
            ApiResponse<Refund> localVarResp = refundPaymentWithHttpInfo(captureId, payPalRequestId, prefer, payPalAuthAssertion, refundRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute refundPayment request with HTTP info returned
         * @return ApiResponse&lt;Refund&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> A successful request returns the HTTP &lt;code&gt;201 Created&lt;/code&gt; status code and a JSON response body that shows refund details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Refund> executeWithHttpInfo() throws ApiException {
            RefundRequest refundRequest = buildBodyParams();
            return refundPaymentWithHttpInfo(captureId, payPalRequestId, prefer, payPalAuthAssertion, refundRequest);
        }

        /**
         * Execute refundPayment request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> A successful request returns the HTTP &lt;code&gt;201 Created&lt;/code&gt; status code and a JSON response body that shows refund details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Refund> _callback) throws ApiException {
            RefundRequest refundRequest = buildBodyParams();
            return refundPaymentAsync(captureId, payPalRequestId, prefer, payPalAuthAssertion, refundRequest, _callback);
        }
    }

    /**
     * Refund captured payment
     * Refunds a captured payment, by ID. For a full refund, include an empty payload in the JSON request body. For a partial refund, include an &lt;code&gt;amount&lt;/code&gt; object in the JSON request body.
     * @param captureId The PayPal-generated ID for the captured payment to refund. (required)
     * @return RefundPaymentRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> A successful request returns the HTTP &lt;code&gt;201 Created&lt;/code&gt; status code and a JSON response body that shows refund details. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
     </table>
     */
    public RefundPaymentRequestBuilder refundPayment(String captureId) throws IllegalArgumentException {
        if (captureId == null) throw new IllegalArgumentException("\"captureId\" is required but got null");
            

        return new RefundPaymentRequestBuilder(captureId);
    }
    private okhttp3.Call showDetailsCall(String captureId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/payments/captures/{capture_id}"
            .replace("{" + "capture_id" + "}", localVarApiClient.escapeString(captureId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call showDetailsValidateBeforeCall(String captureId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'captureId' is set
        if (captureId == null) {
            throw new ApiException("Missing the required parameter 'captureId' when calling showDetails(Async)");
        }

        return showDetailsCall(captureId, _callback);

    }


    private ApiResponse<Capture2> showDetailsWithHttpInfo(String captureId) throws ApiException {
        okhttp3.Call localVarCall = showDetailsValidateBeforeCall(captureId, null);
        Type localVarReturnType = new TypeToken<Capture2>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call showDetailsAsync(String captureId, final ApiCallback<Capture2> _callback) throws ApiException {

        okhttp3.Call localVarCall = showDetailsValidateBeforeCall(captureId, _callback);
        Type localVarReturnType = new TypeToken<Capture2>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ShowDetailsRequestBuilder {
        private final String captureId;

        private ShowDetailsRequestBuilder(String captureId) {
            this.captureId = captureId;
        }

        /**
         * Build call for showDetails
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A successful request returns the HTTP &lt;code&gt;200 OK&lt;/code&gt; status code and a JSON response body that shows captured payment details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return showDetailsCall(captureId, _callback);
        }


        /**
         * Execute showDetails request
         * @return Capture2
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A successful request returns the HTTP &lt;code&gt;200 OK&lt;/code&gt; status code and a JSON response body that shows captured payment details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public Capture2 execute() throws ApiException {
            ApiResponse<Capture2> localVarResp = showDetailsWithHttpInfo(captureId);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute showDetails request with HTTP info returned
         * @return ApiResponse&lt;Capture2&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A successful request returns the HTTP &lt;code&gt;200 OK&lt;/code&gt; status code and a JSON response body that shows captured payment details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Capture2> executeWithHttpInfo() throws ApiException {
            return showDetailsWithHttpInfo(captureId);
        }

        /**
         * Execute showDetails request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A successful request returns the HTTP &lt;code&gt;200 OK&lt;/code&gt; status code and a JSON response body that shows captured payment details. </td><td>  -  </td></tr>
            <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Capture2> _callback) throws ApiException {
            return showDetailsAsync(captureId, _callback);
        }
    }

    /**
     * Show captured payment details
     * Shows details for a captured payment, by ID.
     * @param captureId The PayPal-generated ID for the captured payment to refund. (required)
     * @return ShowDetailsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A successful request returns the HTTP &lt;code&gt;200 OK&lt;/code&gt; status code and a JSON response body that shows captured payment details. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The request failed because an internal server error occurred. </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> The default response. </td><td>  -  </td></tr>
     </table>
     */
    public ShowDetailsRequestBuilder showDetails(String captureId) throws IllegalArgumentException {
        if (captureId == null) throw new IllegalArgumentException("\"captureId\" is required but got null");
            

        return new ShowDetailsRequestBuilder(captureId);
    }
}
